language: cpp
compiler: clang
branches:
    only:
        - main
git:
    depth: 1

matrix:
    include:
        -   os: linux
            dist: bionic
            sudo: required
            name: "Linux Bionic"
            addons:
                apt:
                    packages:
                        - xorg-dev 
                        - libglu1-mesa-dev
                        - liblo-dev
                        - libavcodec-dev 
                        - libavfilter-dev  
                        - libavdevice-dev 
                        - libavformat-dev 
                        - libavutil-dev 
                        - libswscale-dev 
                        - libv4l-dev 
                        - libjpeg-dev 
                        - libpng-dev 
                        - libtiff-dev

        # -   os: osx
        #     name: "MacOS 10.8"
        #     env:
        #         - MACOSX_DEPLOYMENT_TARGET=10.8

# install:
# - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
# - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install liblo ffmpeg; fi

script:
  - mkdir build
  - cd build
  - cmake .. 
  - cmake --build .

# branches:
#   except:
#     - "/^debian\\/\\d/"
# 
# deploy:
#   - provider: launchpad
#     slug: ~patriciogv/glslviewer/+git/glslviewer
#     oauth_token:
#       secure: "OW7GPoeGl8ZPX1ZSXixMgAAhvz2dI3Uif9NnIE7m1A3GMa8ctJKfAULtvjOM/iONYxOZvZeJLmPHYMCY/7L8OdvEJKP4+Dk0qJ/mIfCEKnulTzzjEKvEfos7/0Hjym5D0wVrNZEyiY8rUCm7MDmULHO7BYeBqrJLFJhlr5PZYyY="
#     oauth_token_secret:
#       secure: "A8ZuwfRxu+KsEnU7cMOR2J2DIlQVZO4cPdhXehEZzMXQ/e3/hDkIqw/LicGeR+rIwkG+xgeW1CKdUmXBsptmWhnh8pmSV6xFUXJAFGgaXe7I4WILncHk9AngK7hLRKJjBSjZSkJGGXlTrz7b0esNn9Gyh+QiqZ/CQUhErRwTKNA="